<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AdmissionList extends \AppBundle\Entity\AdmissionList implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'app_no', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'programme', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'course', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'surname', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'othername', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'firstname', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'sex', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'state', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'mstatus', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'inst_name', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'reg_no', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'qual', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'field'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'app_no', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'programme', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'course', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'surname', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'othername', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'firstname', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'sex', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'state', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'mstatus', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'inst_name', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'reg_no', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'qual', '' . "\0" . 'AppBundle\\Entity\\AdmissionList' . "\0" . 'field'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AdmissionList $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAppNo($appNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppNo', [$appNo]);

        return parent::setAppNo($appNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppNo', []);

        return parent::getAppNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setProgramme($programme)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProgramme', [$programme]);

        return parent::setProgramme($programme);
    }

    /**
     * {@inheritDoc}
     */
    public function getProgramme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgramme', []);

        return parent::getProgramme();
    }

    /**
     * {@inheritDoc}
     */
    public function setCourse($course)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCourse', [$course]);

        return parent::setCourse($course);
    }

    /**
     * {@inheritDoc}
     */
    public function getCourse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourse', []);

        return parent::getCourse();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurname($surname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurname', [$surname]);

        return parent::setSurname($surname);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurname', []);

        return parent::getSurname();
    }

    /**
     * {@inheritDoc}
     */
    public function setOthername($othername)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOthername', [$othername]);

        return parent::setOthername($othername);
    }

    /**
     * {@inheritDoc}
     */
    public function getOthername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOthername', []);

        return parent::getOthername();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', [$firstname]);

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', []);

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setSex($sex)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSex', [$sex]);

        return parent::setSex($sex);
    }

    /**
     * {@inheritDoc}
     */
    public function getSex()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSex', []);

        return parent::getSex();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', [$state]);

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', []);

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setMstatus($mstatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMstatus', [$mstatus]);

        return parent::setMstatus($mstatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getMstatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMstatus', []);

        return parent::getMstatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstName($instName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstName', [$instName]);

        return parent::setInstName($instName);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstName', []);

        return parent::getInstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegNo($regNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegNo', [$regNo]);

        return parent::setRegNo($regNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegNo', []);

        return parent::getRegNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setQual($qual)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQual', [$qual]);

        return parent::setQual($qual);
    }

    /**
     * {@inheritDoc}
     */
    public function getQual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQual', []);

        return parent::getQual();
    }

    /**
     * {@inheritDoc}
     */
    public function setField($field)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setField', [$field]);

        return parent::setField($field);
    }

    /**
     * {@inheritDoc}
     */
    public function getField()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getField', []);

        return parent::getField();
    }

}
